name: CI (push master)

on:
  push:
    branches:
      - master
      - main

concurrency:
  group: ci-push-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-reusable.yml
    secrets: inherit
